import { appointments, bookings, currency, inventory, leads, payments, previewRequests, staff } from './demo-data';
import type { CrudModuleConfig, CrudRecord } from '@/components/admin/crud';

const status = (options: string[]) => ({
  key: 'status',
  label: 'Status',
  type: 'select' as const,
  options,
  required: true,
  section: 'Workflow',
});

export const leadCrudConfig: CrudModuleConfig = {
  storageKey: 'rental-admin-leads',
  eyebrow: 'Leads',
  title: 'Lead management',
  description: 'Create, qualify, assign and archive leads before they become appointments or bookings.',
  nextStep: 'Open a lead, update its status, then schedule an appointment or convert to booking.',
  primaryAction: 'Create lead',
  entityLabel: 'Lead',
  createPermission: 'manage_leads',
  updatePermission: 'manage_leads',
  archivePermission: 'manage_leads',
  statusOptions: ['new', 'contacted', 'deposit_requested', 'deposit_received', 'booking_created', 'lost'],
  workflow: ['Lead', 'Appointment', 'Booking'],
  columns: [
    { key: 'title', label: 'Lead' },
    { key: 'request', label: 'Request' },
    { key: 'owner', label: 'Owner' },
    { key: 'status', label: 'Status' },
  ],
  fields: [
    { key: 'title', label: 'Customer name', required: true, section: 'Customer' },
    { key: 'email', label: 'Email', required: true, section: 'Customer' },
    { key: 'phone', label: 'Phone', required: true, section: 'Customer' },
    { key: 'source', label: 'Source', type: 'select', options: ['web', 'walk-in', 'facebook', 'zalo', 'referral'], section: 'Lead context' },
    { key: 'request', label: 'Requested look', required: true, section: 'Lead context' },
    { key: 'budget', label: 'Budget', type: 'number', section: 'Lead context' },
    { key: 'owner', label: 'Owner', type: 'select', options: staff.map((user) => user.name), section: 'Workflow' },
    status(['new', 'contacted', 'deposit_requested', 'deposit_received', 'booking_created', 'lost']),
    { key: 'notes', label: 'Notes', type: 'textarea', section: 'Notes' },
  ],
  seed: leads.map((lead): CrudRecord => ({
    id: lead.id,
    title: lead.customer,
    subtitle: `${lead.source} · ${lead.email}`,
    request: lead.requestedLook,
    owner: lead.staff,
    status: lead.status,
    email: lead.email,
    phone: lead.phone,
    source: lead.source,
    budget: lead.budget,
    notes: lead.notes,
    related: [
      { label: 'Next flow', value: lead.status === 'booking_created' ? 'Create booking' : 'Request deposit' },
      { label: 'Budget', value: currency(lead.budget) },
    ],
    timeline: ['Lead captured', `Assigned to ${lead.staff}`, `Status is ${lead.status}`],
  })),
};

export const appointmentCrudConfig: CrudModuleConfig = {
  storageKey: 'rental-admin-appointments',
  eyebrow: 'Appointments',
  title: 'Appointment calendar',
  description: 'Create, update and archive consultation, fitting, pickup and return appointments.',
  nextStep: 'Filter by staff or type, then open the appointment to update status.',
  primaryAction: 'Create appointment',
  entityLabel: 'Appointment',
  createPermission: 'manage_appointments',
  updatePermission: 'manage_appointments',
  archivePermission: 'manage_appointments',
  statusOptions: ['scheduled', 'checked_in', 'completed', 'cancelled'],
  workflow: ['Lead', 'Appointment', 'Booking'],
  columns: [
    { key: 'title', label: 'Appointment' },
    { key: 'type', label: 'Type' },
    { key: 'owner', label: 'Staff' },
    { key: 'status', label: 'Status' },
  ],
  fields: [
    { key: 'title', label: 'Customer', required: true, section: 'Customer' },
    { key: 'type', label: 'Type', type: 'select', options: ['consultation', 'fitting', 'pickup', 'return'], section: 'Schedule' },
    { key: 'date', label: 'Date', type: 'date', section: 'Schedule' },
    { key: 'time', label: 'Time', section: 'Schedule' },
    { key: 'room', label: 'Room', section: 'Schedule' },
    { key: 'owner', label: 'Staff', type: 'select', options: staff.map((user) => user.name), section: 'Workflow' },
    status(['scheduled', 'checked_in', 'completed', 'cancelled']),
  ],
  seed: appointments.map((appointment): CrudRecord => ({
    id: appointment.id,
    title: appointment.customer,
    subtitle: `${appointment.date} ${appointment.time} · ${appointment.room}`,
    type: appointment.type,
    owner: appointment.staff,
    date: appointment.date,
    time: appointment.time,
    room: appointment.room,
    status: appointment.status,
    related: [{ label: 'Flow', value: appointment.type === 'fitting' ? 'Lead to booking' : 'Booking fulfillment' }],
    timeline: ['Appointment created', `Status is ${appointment.status}`],
  })),
};

export const bookingCrudConfig: CrudModuleConfig = {
  storageKey: 'rental-admin-bookings',
  eyebrow: 'Bookings',
  title: 'Booking management',
  description: 'Manage the full booking lifecycle from draft to payment, pickup, return and completion.',
  nextStep: 'Open a booking and move the status to the next operational stage.',
  primaryAction: 'Create booking',
  entityLabel: 'Booking',
  createPermission: 'manage_bookings',
  updatePermission: 'manage_bookings',
  archivePermission: 'manage_bookings',
  statusOptions: ['draft', 'deposit_requested', 'deposit_received', 'confirmed', 'awaiting_security_deposit', 'awaiting_remaining_payment', 'ready_for_pickup', 'scheduled_pickup', 'picked_up', 'return_pending', 'returned', 'settlement_pending', 'completed', 'cancelled'],
  workflow: ['Booking', 'Payment', 'Pickup', 'Return', 'Receipt'],
  columns: [
    { key: 'title', label: 'Booking' },
    { key: 'item', label: 'Item' },
    { key: 'period', label: 'Period' },
    { key: 'status', label: 'Status' },
  ],
  fields: [
    { key: 'title', label: 'Customer', required: true, section: 'Customer' },
    { key: 'phone', label: 'Phone', section: 'Customer' },
    { key: 'item', label: 'Product / item', required: true, section: 'Items' },
    { key: 'period', label: 'Rental period', section: 'Schedule' },
    { key: 'owner', label: 'Owner', type: 'select', options: staff.map((user) => user.name), section: 'Workflow' },
    status(['draft', 'deposit_requested', 'deposit_received', 'confirmed', 'awaiting_security_deposit', 'awaiting_remaining_payment', 'ready_for_pickup', 'scheduled_pickup', 'picked_up', 'return_pending', 'returned', 'settlement_pending', 'completed', 'cancelled']),
    { key: 'paid', label: 'Paid amount', type: 'number', section: 'Payment' },
    { key: 'deposit', label: 'Deposit', type: 'number', section: 'Payment' },
  ],
  seed: bookings.map((booking): CrudRecord => ({
    id: booking.id,
    title: booking.customer,
    subtitle: booking.id,
    item: `${booking.product} · ${booking.itemCode}`,
    period: `${booking.startDate} to ${booking.endDate}`,
    owner: booking.staff,
    phone: booking.phone,
    status: booking.status,
    paid: booking.paid,
    deposit: booking.deposit,
    related: [
      { label: 'Payment', value: `${currency(booking.paid)} paid` },
      { label: 'Refundable deposit', value: currency(booking.refundableDeposit) },
    ],
    timeline: booking.timeline,
  })),
};

export const paymentCrudConfig: CrudModuleConfig = {
  storageKey: 'rental-admin-payments',
  eyebrow: 'Payments',
  title: 'Payments',
  description: 'Create, verify, refund and archive payment records without losing the booking context.',
  nextStep: 'Open a payment to update status or print the related receipt.',
  primaryAction: 'Create payment',
  entityLabel: 'Payment',
  createPermission: 'process_payments',
  updatePermission: 'process_payments',
  archivePermission: 'process_payments',
  statusOptions: ['pending', 'processing', 'completed', 'failed', 'refunded', 'partially_refunded'],
  workflow: ['Booking', 'Payment', 'Receipt'],
  columns: [
    { key: 'title', label: 'Payment' },
    { key: 'customer', label: 'Customer' },
    { key: 'amount', label: 'Amount', align: 'right' },
    { key: 'status', label: 'Status' },
  ],
  fields: [
    { key: 'title', label: 'Payment ID', required: true, section: 'Payment' },
    { key: 'customer', label: 'Customer', required: true, section: 'Payment' },
    { key: 'bookingId', label: 'Booking ID', section: 'Payment' },
    { key: 'type', label: 'Type', type: 'select', options: ['booking_deposit', 'rental_payment', 'security_deposit', 'fee', 'refund'], section: 'Payment' },
    { key: 'method', label: 'Method', type: 'select', options: ['cash', 'bank_transfer', 'ewallet'], section: 'Payment' },
    { key: 'amount', label: 'Amount', type: 'number', section: 'Payment' },
    status(['pending', 'processing', 'completed', 'failed', 'refunded', 'partially_refunded']),
  ],
  seed: payments.map((payment): CrudRecord => ({
    id: payment.id,
    title: payment.id,
    subtitle: `${payment.bookingId} · ${payment.type}`,
    customer: payment.customer,
    bookingId: payment.bookingId,
    type: payment.type,
    method: payment.method,
    amount: payment.amount,
    status: payment.status,
    related: [
      { label: 'Receipt', value: payment.receiptId ?? 'Not printed' },
      { label: 'Booking', value: payment.bookingId },
    ],
    timeline: ['Payment created', `Status is ${payment.status}`],
  })),
};

export const receiptCrudConfig: CrudModuleConfig = {
  storageKey: 'rental-admin-receipts',
  eyebrow: 'Receipts',
  title: 'Receipts and bills',
  description: 'Create, update, archive and print receipt records for deposits, rentals, returns and refunds.',
  nextStep: 'Open a receipt to print or archive it.',
  primaryAction: 'Create receipt',
  entityLabel: 'Receipt',
  createPermission: 'print_receipts',
  updatePermission: 'print_receipts',
  archivePermission: 'print_receipts',
  statusOptions: ['draft', 'print_ready', 'printed', 'voided'],
  workflow: ['Payment', 'Receipt', 'Print'],
  columns: [
    { key: 'title', label: 'Receipt' },
    { key: 'customer', label: 'Customer' },
    { key: 'type', label: 'Type' },
    { key: 'status', label: 'Status' },
  ],
  fields: [
    { key: 'title', label: 'Receipt number', required: true, section: 'Receipt' },
    { key: 'customer', label: 'Customer', required: true, section: 'Receipt' },
    { key: 'bookingId', label: 'Booking ID', section: 'Receipt' },
    { key: 'type', label: 'Type', type: 'select', options: ['deposit_receipt', 'rental_receipt', 'return_receipt', 'refund_receipt'], section: 'Receipt' },
    { key: 'amount', label: 'Amount', type: 'number', section: 'Receipt' },
    status(['draft', 'print_ready', 'printed', 'voided']),
  ],
  seed: payments.filter((payment) => payment.receiptId).map((payment): CrudRecord => ({
    id: payment.receiptId!,
    title: payment.receiptId!,
    subtitle: payment.bookingId,
    customer: payment.customer,
    bookingId: payment.bookingId,
    type: payment.type === 'refund' ? 'refund_receipt' : payment.type === 'booking_deposit' ? 'deposit_receipt' : 'rental_receipt',
    amount: payment.amount,
    status: 'print_ready',
    related: [{ label: 'Payment', value: payment.id }],
    timeline: ['Receipt generated', 'Ready to print'],
  })),
};

export const inventoryCrudConfig: CrudModuleConfig = {
  storageKey: 'rental-admin-inventory',
  eyebrow: 'Inventory',
  title: 'Inventory',
  description: 'Manage products, variants and individual rentable items with QR, condition and lifecycle status.',
  nextStep: 'Open an item to update status, edit QR details or archive retired stock.',
  primaryAction: 'Create item',
  entityLabel: 'Inventory item',
  createPermission: 'manage_inventory',
  updatePermission: 'manage_inventory',
  archivePermission: 'manage_inventory',
  statusOptions: ['available', 'rented', 'maintenance', 'damaged', 'retired'],
  workflow: ['Inventory', 'QR', 'Pickup', 'Return'],
  columns: [
    { key: 'title', label: 'Item' },
    { key: 'product', label: 'Product' },
    { key: 'condition', label: 'Condition' },
    { key: 'status', label: 'Status' },
  ],
  fields: [
    { key: 'title', label: 'Item code', required: true, section: 'Item' },
    { key: 'product', label: 'Product', required: true, section: 'Product' },
    { key: 'variant', label: 'Variant', section: 'Product' },
    { key: 'size', label: 'Size', section: 'Product' },
    { key: 'qrCode', label: 'QR code', section: 'Item' },
    { key: 'condition', label: 'Condition', type: 'select', options: ['good', 'dirty', 'damaged', 'incomplete'], section: 'Care' },
    { key: 'location', label: 'Location', section: 'Care' },
    status(['available', 'rented', 'maintenance', 'damaged', 'retired']),
    { key: 'maintenanceNote', label: 'Maintenance note', type: 'textarea', section: 'Care' },
  ],
  seed: inventory.map((item): CrudRecord => ({
    id: item.id,
    title: item.itemCode,
    subtitle: item.qrCode,
    product: item.product,
    variant: item.variant,
    size: item.size,
    qrCode: item.qrCode,
    condition: item.condition,
    location: item.location,
    maintenanceNote: item.maintenanceNote,
    status: item.status,
    related: [
      { label: 'Current booking', value: item.currentBooking ?? 'None' },
      { label: 'QR', value: item.qrCode },
    ],
    timeline: item.history,
  })),
};

export const previewCrudConfig: CrudModuleConfig = {
  storageKey: 'rental-admin-preview-requests',
  eyebrow: 'Preview queue',
  title: 'Preview requests',
  description: 'Create, process, update and archive customer preview requests.',
  nextStep: 'Open a pending request, update status, then link it to the booking.',
  primaryAction: 'Create preview request',
  entityLabel: 'Preview request',
  createPermission: 'manage_preview_queue',
  updatePermission: 'manage_preview_queue',
  archivePermission: 'manage_preview_queue',
  statusOptions: ['pending', 'processing', 'completed', 'rejected'],
  workflow: ['Preview request', 'Review', 'Booking'],
  columns: [
    { key: 'title', label: 'Request' },
    { key: 'garment', label: 'Garment' },
    { key: 'requestedAt', label: 'Requested' },
    { key: 'status', label: 'Status' },
  ],
  fields: [
    { key: 'title', label: 'Customer', required: true, section: 'Request' },
    { key: 'garment', label: 'Garment', required: true, section: 'Request' },
    { key: 'requestedAt', label: 'Requested at', section: 'Request' },
    status(['pending', 'processing', 'completed', 'rejected']),
    { key: 'result', label: 'Result note', type: 'textarea', section: 'Result' },
  ],
  seed: previewRequests.map((request): CrudRecord => ({
    id: request.id,
    title: request.customer,
    subtitle: request.id,
    garment: request.garment,
    requestedAt: request.requestedAt,
    result: request.result,
    status: request.status,
    related: [{ label: 'Result', value: request.result }],
    timeline: ['Preview request created', `Status is ${request.status}`],
  })),
};

export const userCrudConfig: CrudModuleConfig = {
  storageKey: 'rental-admin-users',
  eyebrow: 'Users',
  title: 'Users and roles',
  description: 'Create users, update roles, archive inactive staff and keep role permissions clear.',
  nextStep: 'Open a user to update role or archive access.',
  primaryAction: 'Invite user',
  entityLabel: 'User',
  createPermission: 'manage_users',
  updatePermission: 'manage_users',
  archivePermission: 'manage_users',
  statusOptions: ['active', 'disabled'],
  workflow: ['User', 'Role', 'Permission'],
  columns: [
    { key: 'title', label: 'User' },
    { key: 'role', label: 'Role' },
    { key: 'workload', label: 'Workload', align: 'right' },
    { key: 'status', label: 'Status' },
  ],
  fields: [
    { key: 'title', label: 'Full name', required: true, section: 'Profile' },
    { key: 'email', label: 'Email', required: true, section: 'Profile' },
    { key: 'role', label: 'Role', type: 'select', options: ['super_admin', 'manager', 'sales', 'operator', 'cashier'], section: 'Access' },
    { key: 'workload', label: 'Workload', type: 'number', section: 'Access' },
    status(['active', 'disabled']),
  ],
  seed: staff.map((user): CrudRecord => ({
    id: user.id,
    title: user.name,
    subtitle: user.email,
    email: user.email,
    role: user.role,
    workload: user.workload,
    status: user.active ? 'active' : 'disabled',
    related: [{ label: 'Role', value: user.role }],
    timeline: ['User created', `Role assigned: ${user.role}`],
  })),
};
